services:
  cartapi:
    build:
      context: ..
      dockerfile: src/Abysalto.CartApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Db=Host=db;Port=5432;Database=cartdb;Username=cart;Password=cart
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=cartdb
      - POSTGRES_USER=cart
      - POSTGRES_PASSWORD=cart
    ports:
      - "5432:5432"
